Refactor post_authors indexer to avoid repeated calls to the catalog
collective/collective.blog pull request #57
Opened 2024-02-01 14:48 UTC by ericof

Fix #56

2024-02-01 21:35 UTC, davisagli requested changes

2024-02-01 21:35 UTC, davisagli commented on src/collective/blog/indexers/post.py
> +        authors.append(brain.title)
The catalog metadata has Title capitalized:

```suggestion
        authors.append(brain.Title)
```

2024-02-01 22:01 UTC, ericof commented
Good call, I will update the PR

On Thu, Feb 1, 2024, 18:36 David Glick ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/collective/blog/indexers/post.py
> <https://github.com/collective/collective.blog/pull/57#discussion_r1475181393>
> :
>
> > @@ -15,12 +15,7 @@ def post_authors(obj: Post):
>      """Returns the authors of a blog post."""
>      authors = []
>      uids = obj.creators
> -    for uid in uids:
> -        searchResult = api.content.find(portal_type="Author", UID=uid)
> -        if len(searchResult) > 0:
> -            author = searchResult[0].getObject()
> -
> -            if author is not None:
> -                authors.append(author.title)
> -
> +    brains = api.content.find(portal_type="Author", UID=uids)
> +    for brain in brains:
> +        authors.append(brain.title)
>
> The catalog metadata has Title capitalized:
> ⬇️ Suggested change
>
> -        authors.append(brain.title)
> +        authors.append(brain.Title)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/collective/collective.blog/pull/57#pullrequestreview-1857685343>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACKWXQDF4PC3RNSV7M46JLYRQDEDAVCNFSM6AAAAABCVBHBVKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNJXGY4DKMZUGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-02 10:02 UTC, jonaspiterek commented
I tested it locally and the upgrade step was broken, pushed a fix.

2024-02-02 10:02 UTC, jonaspiterek reviewed
LGTM

2024-02-02 12:39 UTC, merged

2024-02-02 18:33 UTC, davisagli commented
@jonaspiterek thanks, good catch